### ISSUE TITLE
New greeter doesn't remember last user

### ISSUE THREAD

**Issue by janxkoci** [elementary/greeter#341] opened 2019-08-31 08:51 UTC
The old greeter could remember which user last logged in and showed that user by default. The new greeter seems to always show the first user (alphabetically). This is the case for both cold boot and lock screen.

Since the new greeter fixed several issues of the old one, especially keyboard navigation issues, it's now easy to select the right user, but it can be improved.

**Comment by davidmhewitt** [comment] 2019-08-31 10:03
Hi, thanks for the report!

This is a duplicate of #204 and a fix is in the works.

**Closed by davidmhewitt** 2019-08-31 10:03 UTC
Labels: Status: Duplicate

**Comment by janxkoci** [comment] 2019-09-01 15:49
Ah I didn't notice, thanks
