### ISSUE TITLE
Greeter extends period monitor is active for, doesn't turn off quickly

### ISSUE THREAD

**Issue by ryanrms** [elementary/greeter#313] opened 2019-07-15 04:59 UTC
Setup:
elementary OS Juno set to lock and turn off screen at 10 minutes

What happens:
10 minutes ticks by, screen turns off (good).  Lock screen/greeter kicks in, screen turns on (bad).  Another 10 minutes ticks by and then screen finally turns off and stays off for the night.

Ideal behaviour:
Screen turns off after 10 minutes, greeter locks the screen without turning the display(s) back on.
OR greeter appears briefly but then turns off the display quite quickly (talking 30 seconds of inactivity or some small value, something similar to what the GNOME greeter does.)

I tried su-ing into the lightdm user and changing the gsettings key org.gnome.desktop.session idle-delay to 30 seconds, but it doesn't appear to have an effect on the greeter.  Would another key be responsible for this timing?

**Comment by ryanrms** [comment] 2019-07-15 05:20
Found a workaround to turn the screen off, from this AskUbuntu post:
https://askubuntu.com/questions/403859/how-to-control-lightdm-power-saving-preferences

/etc/lightdm/lightdm.conf.d/50-dpms.conf

```
[SeatDefaults] 
display-setup-script=/etc/lightdm/dpms-enable
session-setup-script=/etc/lightdm/dpms-disable
```
Make sure the above is owned by root. Easiest is to create it with sudoedit.

Next are the two scripts. These need to be owned by root and made executable (chmod +x).

/etc/lightdm/dpms-enable

```
#!/bin/sh

(
    # This delay is required. Might be because the X server isn't
    # started yet.
    sleep 10

    # Set up a 5 minute timeout before powering off the display.
    xset dpms 0 0 300 
) &
```
/etc/lightdm/dpms-disable
```
#!/bin/sh

(
    # This delay is required. Might be because the X server isn't
    # started yet.
    sleep 10

    # Turn off X's handling of dpms timeout. Otherwise
    # gnome-settings-daemon and gnome-screensaver will fight over it.
    xset dpms 0 0 0 
) &

```

I changed the dpms-enable script to a value of 15 seconds, and it is working nicely for me.

**Comment by peteruithoven** [comment] 2019-07-15 09:39
Isn't this a duplicate of https://github.com/elementary/greeter/issues/161 ?

**Comment by ryanrms** [comment] 2019-07-15 17:04
It's related, but not quite the same.  That issue appears to be with the greeter not respecting power settings such as turn off display and suspend.  I've found a workaround for stopping the suspend behavior, but this issue is about the screen not turning off in a reasonable fashion after locking.

**Comment by peteruithoven** [comment] 2019-07-15 17:11
> but this issue is about the screen not turning off in a reasonable fashion after locking.

But isn't that also a power setting?

**Comment by ryanrms** [comment] 2019-07-15 17:16
> But isn't that also a power setting?
I don't want it to respect my power setting of 10 minutes to screen turn off, I want it to turn off almost immediately. Otherwise the screen stays on for 20 minutes instead of 10.  I don't want this behavior on the desktop obviously.

**Comment by Blast-City** [comment] 2019-08-04 14:12
#261

**Comment by Blast-City** [comment] 2019-08-06 21:31
I tested this on two computers and strangely they show different behaviours. On one the monitor turns off after 60 seconds, but the other i see the same issue as this thread.

Both have the same lightdm options in /etc/lightdm/io.elementary.greeter.conf.

**Comment by danrabbit** [comment] 2021-06-18 17:01
This seems to be resolved in OS 6 beta 2 since we've done the big rewrite of screen locking and syncing power settings and all that.

Closing since I believe this was fixed. Please reopen if you can still reproduce this issue on OS 6 :)

**Closed by danrabbit** 2021-06-18 17:01 UTC
