### ISSUE TITLE
Shutdown popup is inconsistent

### ISSUE THREAD

**Issue by aubreybourke** [elementary/greeter#267] opened 2019-04-10 14:03 UTC
When logged in, if you select shutdown, you are presented with a popup to confirm your choice. This popup doesn't have a title bar.

However, when you do this from the login screen the popup has a title bar.

Personally I prefer the title bar, and would like to see all popups use a title bar.

**Comment by tintou** [comment] 2019-04-10 14:07
Duplicate of #118

**Closed by tintou** 2019-04-10 14:07 UTC

**Comment by aubreybourke** [comment] 2019-04-11 00:14
Not sure if its a duplicate of the compositor issue.

Here's a screenshot of a standard popup
![Screenshot from 2019-04-10 14-28-33](https://user-images.githubusercontent.com/49486422/55921939-ef840580-5bf6-11e9-8854-d2ccc3c03319.png)

And here's the same popup on the greeter
![20190410_143059](https://user-images.githubusercontent.com/49486422/55921965-104c5b00-5bf7-11e9-9beb-62bcc9f326c2.jpg)

**Comment by cassidyjames** [comment] 2019-04-11 01:07
@aubreybourke yep, that's the same issue.
