### ISSUE TITLE
Wingpanel does not follow the system color pattern on the lock screen

### ISSUE THREAD

**Issue by wandertorres** [elementary/greeter#234] opened 2019-02-22 13:21 UTC
The default behavior of the wingpanel, from turning white to dark backgrounds and black to light backgrounds, is not followed by the lock screen.

Another component that does not follow the pattern on the lock screen is the hour display, which shows AM / PM even in the 24 hour standard.

**Comment by danrabbit** [comment] 2019-03-28 23:49
Thanks for your report! We're doing a from-scratch rewrite of the Greeter and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of the Greeter

**Closed by danrabbit** 2019-03-28 23:49 UTC
