### ISSUE TITLE
I can't disable guest account

### ISSUE THREAD

**Issue by sergiocin** [elementary/greeter#232] opened 2019-02-09 18:54 UTC
I am using Juno and I can't disable guest account, I already disabled guest account in system settings, but nothing happen, so I used nano to change greeter settings to allow-guest to false. There is the file: /usr/share/lightdm/lightdm.conf.d/40-io.elementary.greeter.conf.

Did I do something wrong? I just add the line allow-guest=false to the end of the file.

**Comment by sergiocin** [comment] 2019-02-09 21:59
I just edited the file 60-guest-session.conf in the same folder, I wrote the same line at the end of the file, this disabled guest account, but the switch gui is still not working for enable and disable.

**Comment by danrabbit** [comment] 2019-03-06 21:21
Thanks for your report! We're doing a from-scratch rewrite of the Greeter and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Greeter.

**Closed by danrabbit** 2019-03-06 21:21 UTC
