### ISSUE TITLE
User icon only draws in top left quadrant of circle on HiDPI displays

### ISSUE THREAD

**Issue by JPLeBreton** [elementary/greeter#62] opened 2017-07-24 18:19 UTC
I have my desktop running at 2x scale on this laptop's HiDPI display. Everything looks fine except for my user icon, a 256x256 PNG image, on the greeter:
https://www.dropbox.com/s/zigpeevoyejjm7j/elem_greeter_icon.jpg?dl=0

I realize the top panel is not part of the greeter but it draws the same erroneous way there too, seems possibly related:
https://www.dropbox.com/s/0ryn2x4xld8ectq/elem_user_icon.jpg?dl=0

**Comment by davidmhewitt** [comment] 2017-07-24 18:39
Thank you for the report. This is a partial duplicate of #7.

Has been fixed in https://github.com/elementary/granite/pull/75 .

So this should be fixed when the next release of Granite comes around.

**Closed by davidmhewitt** 2017-07-24 18:39 UTC

**Comment by naftulikay** [comment] 2017-12-28 19:30
@davidmhewitt @danrabbit Is there an update on when this package will be shipped to Loki?
