### ISSUE TITLE
desktop freezes after return from suspension

### ISSUE THREAD

**Issue by mustafaREIMAHG** [elementary/greeter#198] opened 2018-11-15 19:19 UTC
After waking up few seconds (almost 3 secs) wifi is reconnecting successfully, Then the screen freezing completely. I have to force restart my machine 
This issue happens often.

**Comment by kgrubb** [comment] 2019-10-01 04:02
This looks to be a duplicate of #78

**Closed by kgrubb** 2019-10-01 04:02 UTC
