### ISSUE TITLE
"New" Greeter is not using correct locale.

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/greeter#298] opened 2019-06-28 05:26 UTC
Hi.

After installing "new" Greeter I'm happy to see that the AM/PM is finally fixed for my locale (I was having both 24h format with AM/PM) but unfortunately now I'm having day and month displayed in the English language which was working fine in the "stable" version.

**Comment by peteruithoven** [comment] 2019-06-28 11:43
I assume the issue is that it doesn't follow user settings in general, like other issues listed in the following project:
https://github.com/elementary/greeter/projects/2

**Comment by danrabbit** [comment] 2019-06-28 16:12
The Greeter now [gets its translations for the date format](https://github.com/elementary/greeter/blob/master/src/DateTimeWidget.vala#L49) from Granite, so you'll want to make sure date formats are translated for your locale in [Weblate](https://l10n.elementary.io/projects/desktop/granite/)

If you're not already a member of the translation team for your locale, please let me know and I can approve you as one :)

Closing this issue since this is now handled in Granite and thus `Out of Scope`

**Closed by danrabbit** 2019-06-28 16:12 UTC

**Comment by WebShapedBiz** [comment] 2019-06-28 16:17
The formats are translated because:
a) the last stable version of Greeter was translated correctly.
b) after login everything is translated correctly.

This was very quick dismissal, sorry to have bothered you, I won't be making the same mistake again. If it was due to the Granite translations there wouldn't be a) and b). You can leave this closed.

**Comment by peteruithoven** [comment] 2019-06-28 18:24
Please understand that we get a lot of issues. So please don't feel discouraged when we're a bit quick to close issues. 
a) Granite has changed in the mean time, so this fact probably doesn't impact how it works in the old Greeter. 
b) After login? You mean in the Wingpanel for example?

**Comment by danrabbit** [comment] 2019-06-28 18:38
Hey @WebShapedBiz, sorry if I was unclear in my response. The old greeter design handled translations itself and did not use Granite for these date formats. Only the new greeter uses Granite to fetch date formats.

Can you make doubly sure that these formats have already been localized correctly for your language on Weblate? They may have been translated for the old Greeter, but not for Granite. https://l10n.elementary.io/projects/desktop/granite/

Can you also verify that you have set the system language (in addition to your user's language) to the desired locale in System Settings → Location & Region?
