### ISSUE TITLE
GTK theme override outdated (new theme names / colors)

### ISSUE THREAD

**Issue by decathorpe** [elementary/greeter#444] opened 2020-06-07 10:34 UTC
greeter still sets the theme to `elementary`, which does not exist anymore:

https://github.com/elementary/greeter/blob/master/src/MainWindow.vala#L75

I suspect this should be changed to `io.elementary.stylesheet.blueberry` at some point to match the new default setting?

**Comment by cassidyjames** [comment] 2020-06-07 17:14
Yep, duplicate of #435. ;)

**Closed by cassidyjames** 2020-06-07 17:14 UTC
