### ISSUE TITLE
Theme is not applied

### ISSUE THREAD

**Issue by ziflex** [elementary/greeter#48] opened 2017-06-18 18:31 UTC
Hi there,

I'm running Pantheon DE on Fedora and experiencing an issue with the greeter's styling. 
The issue is that when I LightDM runs the greeter its css styles are not picked up. But, when I run the greeter just as an application - everything is fine.
Probably, I missed something in LightDM configuraton.

**Comment by danrabbit** [comment] 2017-06-18 18:33
This should probably have been resolved in #41 

Can you confirm the issue persists with Greeter from master?

**Comment by ziflex** [comment] 2017-06-20 14:10
Unfortunately, I can't install it from master. 
I follow the instructions but it complains that my system doesn't have required dependencies, when it does.

**Comment by cassidyjames** [comment] 2018-12-21 18:07
Closing due to inactivity. If this is still an issue that can be reproduced, feel free to reopen.

**Closed by cassidyjames** 2018-12-21 18:07 UTC
Labels: Status: Incomplete
