### ISSUE TITLE
The localized time on the welcome screen is shown in the wrong format

### ISSUE THREAD

**Issue by vadbars** [elementary/greeter#223] opened 2018-12-21 18:08 UTC
The localized time on the welcome screen is shown in the wrong format.
Localized time in Russian is shown as 12:23 П.П. instead 12:23

**Comment by danrabbit** [comment] 2018-12-21 18:11
Closing as a duplicate of #17

**Closed by danrabbit** 2018-12-21 18:11 UTC

**Comment by vadbars** [comment] 2018-12-21 18:19
An error occurs in elementary OS 5.0 Juno. The same as a year ago in Loki. )
