### ISSUE TITLE
Brightness keys don't work

### ISSUE THREAD

**Issue by gorghino** [elementary/greeter#104] opened 2018-05-03 09:24 UTC
I'm not sure it's a bug but it's annoying imho.
If you remove brightness in your session and the laptop goes to suspension, after resuming the screen is dark/black but fn+brightness up doesn't work in the login screen. 
To unlock you need to supposed that nothing wrong happened and type the password; only after that you can increase the brightness.

**Comment by danrabbit** [comment] 2018-11-14 23:48
Fixed in https://github.com/elementary/greeter/commit/fd36f26b22a79162f628f687e72770df4e547f5c

**Closed by danrabbit** 2018-11-14 23:48 UTC
Labels: Status: Confirmed

**Comment by inad9300** [comment] 2020-03-01 15:59
I would like to report another instance of this issue. I'm not sure if this is specific to the computer I'm using, since I haven't ever seen this feature working, but I can confirm that brightness keys are at the moment not working on a Microsoft Surface Pro 3, whose keyboard offers direct access to function keys by default. Holding "Fn" while pressing the brightness keys doesn't work either.
