### ISSUE TITLE
Compositor spawn Greeter's Window in the secondary monitor

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary/greeter#141] opened 2018-07-12 02:43 UTC
When using a secondary monitor, Wingpanel and cursor is spawned in the primary monitor, although the Greeter Window is spawned in the secondary monitor. Those components should be all in the primary monitor.

![photo_2018-07-11_23-37-52](https://user-images.githubusercontent.com/828559/42609615-c5f9bf4e-8563-11e8-94f0-e58f72c8bc1f.jpg)

**Comment by croozey** [comment] 2018-07-17 04:34
Nothing to add - just confirming this is happening to me also.

**Comment by toshe** [comment] 2018-07-22 06:03
Is that #65?

**Comment by peteruithoven** [comment] 2019-03-19 10:41
Seems like a duplicate of #65 indeed

**Closed by peteruithoven** 2019-03-19 10:41 UTC
Labels: Status: Confirmed
