### ISSUE TITLE
Time isn't displayed in 24h format, despite setting in switchboard

### ISSUE THREAD

**Issue by jtrees** [elementary/greeter#52] opened 2017-06-28 16:42 UTC
In the System Settings, I set the time format to 24h but greeter ignores this.

**Comment by jtrees** [comment] 2017-06-28 16:42
Related: https://github.com/elementary/greeter/issues/17

**Comment by vjr** [comment] 2017-06-29 16:04
The correct PR link is https://github.com/elementary/greeter/pull/53

**Comment by jtrees** [comment] 2017-07-03 08:36
Cool thanks. I look forward to this being merged.

**Comment by richo67** [comment] 2017-10-20 07:50
When will this be merged? When we can see that in use? Thanks

**Comment by jlnr** [comment] 2018-05-22 21:01
Besides using the wrong format, the time string is also clipped on German systems now (running at 4K):

![greeter](https://user-images.githubusercontent.com/70772/40164810-d5e4cd60-59ba-11e8-9a00-41a9c81d5875.jpg)

I think this is new, and it used to say "vorm." instead of "vormittags".

**Comment by danrabbit** [comment] 2018-11-13 05:39
Closing as a duplicate of #17

**Closed by danrabbit** 2018-11-13 05:39 UTC
Labels: Priority: High, Status: Confirmed
