### ISSUE TITLE
Writing goes over the screen

### ISSUE THREAD

**Issue by Jason5679** [elementary/greeter#183] opened 2018-11-07 21:36 UTC
I use the german translation of elementary os (juno) and when its pm the date protrudes over the screen. Anyway in Germany we don't need the classification in afternoon and evening, because we have a 24h-system (1pm is 13 o clock). This is not a hardware problem. Does not work on both of my computers.

**Comment by peteruithoven** [comment] 2018-11-07 22:17
Thanks for the report! Isn't this a duplicate of https://github.com/elementary/greeter/issues/159 ?

Anyway, we're working on a big rewrite: https://github.com/elementary/greeter/pull/181

**Closed** 2018-11-07 22:17 UTC
Labels: Status: Duplicate
