### ISSUE TITLE
freeze after lock screen

### ISSUE THREAD

**Issue by rizkyramadhanch** [elementary/greeter#348] opened 2019-09-03 07:39 UTC
for a moment a lock my elementary os, then i try to relogin, it can't type anything on my user account, also i can't use my fingerprint to login.

please help me
thank you so much :*

**Comment by pmop** [comment] 2019-09-30 06:39
Can confirm. I'll be bringing the logs soon.

**Comment by pmop** [comment] 2019-10-01 03:10
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1788018 seems to be the culprit here, at least for me.

**Comment by pmop** [comment] 2019-10-01 03:12
Isn't this issue dupe with #198 and #78?

**Comment by kgrubb** [comment] 2019-10-01 04:02
duplicate of #78

**Closed by kgrubb** 2019-10-01 04:02 UTC
