### ISSUE TITLE
Broken HiDPI Profile Image Rendering

### ISSUE THREAD

**Issue by naftulikay** [elementary/greeter#84] opened 2017-12-18 18:56 UTC
As originally reported [here](https://bugs.launchpad.net/bugs/1737848), I'm seeing my profile image rendered at one quarter of the size it should be:

![](https://i.imgur.com/v8iYrNd.jpg)

I was told that this was fixed, but I still see the issue on a fully updated Loki.

**Comment by danrabbit** [comment] 2017-12-28 18:15
Closing as a duplicate of #62

**Closed by danrabbit** 2017-12-28 18:15 UTC
