### ISSUE TITLE
Greeter is broken

### ISSUE THREAD

**Issue by FernandoGarcia** [elementary/greeter#321] opened 2019-08-13 17:51 UTC
Hi!

I have compiled and installed Greeter according to README but something seems wrong.

The login screen doesn't looks as shown [here](https://github.com/elementary/greeter/pull/219).

When caps lock or num lock are pressed the password input gives a small "jump".

![20190813_131628](https://user-images.githubusercontent.com/2778501/62963772-00789980-bdd8-11e9-8a53-a918bc0dc407.jpg)

I was trying to fix the useless AM/PM in time but now it's so much worst. :(

When there's only 1 user it should look like this? Without wingpanel obviously?

![](https://user-images.githubusercontent.com/611168/53656436-75805a00-3c10-11e9-8f38-570816630cc8.jpg)

How to fix it please?

Here the full log.

[Lightdm.log.zip](https://github.com/elementary/greeter/files/3498222/Lightdm.log.zip)

Best regards.

**Comment by cassidyjames** [comment] 2019-08-13 18:15
@FernandoGarcia are you on elementary OS Juno? Do you have the elementary stylesheet installed?

**Comment by FernandoGarcia** [comment] 2019-08-13 18:29
@cassidyjames I'm using Juno. Dunno I'll try right now.

**Comment by FernandoGarcia** [comment] 2019-08-13 18:45
@cassidyjames I have installed it but I don't how to use Gtk Inspector to test. The installation had not result even after reboot.

**Comment by FernandoGarcia** [comment] 2019-08-14 17:52
Installing Greeter via daily ppa the result is the same.

**Comment by tintou** [comment] 2019-08-19 16:45
You likely have an issue with the theme version, can you try with the latest one?

**Comment by FernandoGarcia** [comment] 2019-08-19 16:53
Hi @tintou!

Since I have posted this issue there's only this commit: https://github.com/elementary/greeter/commit/faa867b4a84b16e80d56f8d7478b69c270787f02

This is not seems related to my problem.

Best regards.

**Comment by tintou** [comment] 2019-08-19 16:55
The answer might be in /var/log/lightdm/lightdm.log

**Comment by FernandoGarcia** [comment] 2019-08-19 17:17
This log is on zip above.

**Comment by tintou** [comment] 2019-08-19 17:35
@FernandoGarcia this is not the same as running it natively on your computer unfortunately

**Comment by FernandoGarcia** [comment] 2019-08-19 17:50
Some package is changing Greeter behaviour.

When there's no selected image the avatar is round otherwise it's square.

![20190814_145438](https://user-images.githubusercontent.com/2778501/63287282-6198e500-c290-11e9-838a-d7edb0219a22.jpg)

![20190814_145553](https://user-images.githubusercontent.com/2778501/63287288-66f62f80-c290-11e9-9bc0-e9b47cd2a054.jpg)

In fresh install in a virtual machine it's ok.

![greete1](https://user-images.githubusercontent.com/2778501/63287383-91e08380-c290-11e9-9427-886e368575cc.png)

I'll try daily ppa in VM.

**Comment by FernandoGarcia** [comment] 2019-08-19 18:34
In my VM it's ok.

![Greeter ok](https://user-images.githubusercontent.com/2778501/63289947-b2abd780-c296-11e9-9abb-6e5000e1879b.png)

**Comment by FernandoGarcia** [comment] 2019-08-19 19:26
How I can purge all settings of Lightdm and Greeter to reinstall everything?

Just `sudo apt purge lightdm && sudo apt purge pantheon-greeter` doesn't solve the problem.

**Comment by FernandoGarcia** [comment] 2019-08-19 21:10
Here the log for current session in real machine.

[lightdm.log](https://github.com/elementary/greeter/files/3517682/lightdm.log)

**Comment by danrabbit** [comment] 2021-06-20 02:31
I'm gonna close this because it's really old and it looks like there was just an issue with this person's installation not having the stylesheet

**Closed by danrabbit** 2021-06-20 02:31 UTC
Labels: Status: Incomplete

**Comment by FernandoGarcia** [comment] 2021-06-20 02:55
Hi!

I'm facing this problem until now.

Right now I have installed the [Stylesheet](https://github.com/elementary/stylesheet) from source and the problem persists.

Can you suggest me another solution?

Best regards.

**Comment by danrabbit** [comment] 2021-06-20 23:32
@FernandoGarcia are you able to reproduce this on a clean installation of elementary OS 5.1.7 (the latest stable version)? It looks like from your previous comments that it was only reproducible on an older installation and a fresh installation didn't have this issue

**Comment by FernandoGarcia** [comment] 2021-06-21 12:45
Hi!
In fresh install it doesn't happens.
It happened to me after an upgrade using sources from this repository and now I can't figure out how to fix.
I have uninstalled Greater several times and installed again with no luck.
Best regards.

**Comment by davidmhewitt** [comment] 2021-06-21 13:01
@FernandoGarcia You can use these instructions to see what packages have been modified from their original installed versions:
https://elementary.io/docs/code/os-dev#restoring-original-packages

Once you have a list of those packages, reinstall any that are related to the greeter and the stylesheet. Also check that there aren't any greeter or stylesheet packages installed somewhere inside `/usr/local`.

We can't really give much more help as this is a unique problem caused by custom installed greeter/stylesheet packages.

**Comment by FernandoGarcia** [comment] 2021-06-26 14:00
Hi!

Unfortunately there's no missing or modified file related to StyleSheet or Greeter.

Thanks for your answer.

Best Regards.
