### ISSUE TITLE
Screen turns black/locks while using live image, unable to unlock

### ISSUE THREAD

**Issue by Coshibu** [elementary/greeter#151] opened 2018-08-17 19:56 UTC
I used elementary Loki as a live image on an usb stick to make changes to partition on a dell xps 15 9560. The screen locked and turned black, while performing a partition move in gparted taking >1hr. There is no way to wake the screen again. The only hope is to wait 2hrs, hope that the process completed and hard poweroff the computer.

Suggestion: turn of screen lock on live image.

**Comment by codygarver** [comment] 2018-08-17 20:01
Duplicate of elementary/os#91

**Closed by codygarver** 2018-08-17 20:01 UTC
