### ISSUE TITLE
Make the login card bigger

### ISSUE THREAD

**Issue by sirsleon** [elementary/greeter#548] opened 2021-08-14 04:34 UTC
## Problem

Login card = Wallpaper, name and login box location

There's so much empty space in the lockscreen, the login card only takes up about 10% of the screen.

## Proposal

A setting in system settings that lets you choose how big the card should be (Medium (Current), Large, Larger)

## Prior Art

in Windows the login area takes up around 20-35% of the screen, much better for people who can't see small details.

Lenovo Yoga 370, elementary OS 6, 1920 x 1080 13" screen

**Comment by ahoneybun** [comment] 2021-12-27 02:28
This would help with larger displays where it shrinks the wallpaper preview like with my 34" 3440x1440 monitor.

**Comment by ahoneybun** [comment] 2021-12-29 01:07
For this issue I feel like it's connected to this one: https://github.com/elementary/greeter/issues/303

**Comment by lenemter** [comment] 2024-01-27 15:10
Duplicate of https://github.com/elementary/greeter/issues/303

**Closed by lenemter** 2024-01-27 15:10 UTC
