### ISSUE TITLE
Setting specific wallpaper

### ISSUE THREAD

**Issue by kepicorp** [elementary/greeter#257] opened 2019-03-28 18:39 UTC
The parameter exist but is not taken into account:
[greeter]
#activate-numlock=true
default-wallpaper=/usr/share/backgrounds/lock.jpg
#high-contrast=false
#onscreen-keyboard=false
#screensaver-timeout=60

**Comment by danrabbit** [comment] 2019-06-28 23:52
Closing as a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/28

**Closed by danrabbit** 2019-06-28 23:52 UTC
