### ISSUE TITLE
Screen upside down from start or wakeup.

### ISSUE THREAD

**Issue by igeglits** [elementary/greeter#690] opened 2023-12-25 08:25 UTC
### What Happened?

The screen is upside down. Every time I turn on or wake up from sleep mode, the login screen appears rotated 180 degrees, and after entering the password and loading to the desktop, the desktop itself is rotated 180 degrees. I have to manually rotate the screen back to normal through the display settings menu each time.

### Steps to Reproduce

1. start PC
2. wait for password screen appears (the screen upside down)
3. enter password
4. wait for desktop screen

### Expected Behavior

Screen is in a normal state - do not rotated 180 degrees.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Asus Flip C302 Chromebook

**Comment by lenemter** [comment] 2023-12-25 08:28
I think the issue here is that greeter doesn't remember screen rotation settings and monitor configuration (https://github.com/elementary/greeter/issues/216 and https://github.com/elementary/greeter/issues/65)

**Comment by lenemter** [comment] 2024-01-27 14:19
Closing as duplicate of https://github.com/elementary/greeter/issues/216

**Closed by lenemter** 2024-01-27 14:19 UTC
