### ISSUE TITLE
Greeter can be force quit when unresponsive

### ISSUE THREAD

**Issue by thomorl** [elementary/greeter#227] opened 2019-01-08 05:08 UTC
My computer is a bit slow, and sometimes, programs are unresponsive. But the greeter, being the first program to be awoken when the sleep mode ends, is "unresponsive" virtually every time I exit the sleep mode, and I get the usual "io.elementary.greeter is unresponsive" system pop-up.
So far just annoying, but the worst part is that the greeter can be closed by pressing the "Force Quit" button on this dialog, making it impossible to log in. Could this please be fixed, either by avoiding the dialog altogether or by making the user unable to force quit the greeter?

Related: #124

**Comment by peteruithoven** [comment] 2019-03-19 10:08
@thomorl could you check whether this is still an issue with the latest version (the one that hasn't been released yet)? Looks like #241 might have fixed the issue

**Comment by danrabbit** [comment] 2019-03-28 00:34
Since we haven't gotten any feedback from OP, gonna close this as incomplete. Feel free to reopen if the issue can be reproduced :)

**Closed by danrabbit** 2019-03-28 00:34 UTC

**Comment by thomorl** [comment] 2019-03-31 08:25
> @thomorl could you check whether this is still an issue with the latest version (the one that hasn't been released yet)? Looks like #241 might have fixed the issue

It is not an issue anymore, the latest version seems to have fixed it.
(Excuse me for answering so late)

**Comment by thomorl** [comment] 2019-05-11 02:39
> > @thomorl could you check whether this is still an issue with the latest version (the one that hasn't been released yet)? Looks like #241 might have fixed the issue
> 
> It is not an issue anymore, the latest version seems to have fixed it.
> (Excuse me for answering so late)

Sadly, the issue reappeared today, although I haven't seen it in a long time. Whenever the greeter takes longer to show itself (too long, apparently), the system thinks its unresponsive and shows the typical "Program is unresponsive" dialog. The problem still is that the greeter can be quit from this dialog, and after that I can't login easily, because I can not reopen the greeter without switching to one of the terminal sessions.
