### ISSUE TITLE
Font in shut down menu and dialog box not Open Sans

### ISSUE THREAD

**Issue by katiemkblaede** [elementary/greeter#99] opened 2018-04-25 21:20 UTC
It looks like the font in the shut down menu and consequent dialog box are not Open Sans. I don't actually know what they are, and I have no way of confirming this because I don't possess the skills to figure out how to do it. @cassidyjames strongly encouraged me to file this bug report myself, so here it is in all its amateur glory. Thanks for your time.

**Comment by cassidyjames** [comment] 2018-04-25 21:29
Is this something to do with not running a compositor, so GTK isn't getting the correct font settings?

**Comment by cassidyjames** [comment] 2018-04-25 21:33
It's possible it's just lacking proper hinting…

Here's what I'm seeing in Juno on the lock screen:

![img_20180425_152552](https://user-images.githubusercontent.com/611168/39273916-82d03caa-489d-11e8-9bc4-cc2c15ce4126.jpg)

Here's a screenshot of the same dialog from the session:

![nt7wfqr](https://user-images.githubusercontent.com/611168/39273939-9964d624-489d-11e8-8a52-cef66a66c663.png)

Note that this is not reproducible by running `pantheon-greeter` from the Terminal in a normal session, because we have a compositor then.

**Comment by danrabbit** [comment] 2018-04-27 23:17
@cassidyjames can you see if this is fixed with #82 ?

**Closed** 2018-05-02 22:54 UTC
Labels: Status: In Progress
