### ISSUE TITLE
Add mouse scroll up/down navigation to move to next user

### ISSUE THREAD

**Issue by vjr** [elementary/greeter#281] opened 2019-05-27 12:08 UTC
Similar to what was on the "old" greeter, even though the user list moves left/right, the mouse scroll up or down should also move to the next user.

**Comment by danrabbit** [comment] 2019-05-27 23:39
This is probably a duplicate of #233 or at least any solution should take that behavior into account as well since it's very related

**Closed** 2019-06-08 00:29 UTC
Labels: Status: In Progress
