### ISSUE TITLE
Kernel 4.4.0-92-generic segfaults Pantheon-Greeter

### ISSUE THREAD

**Issue by eumario** [elementary/greeter#66] opened 2017-08-23 00:48 UTC
On my desktop system, I've done an upgrade of the system, and am running on the elementary-os/daily repo, for the latest packages.  A recent update for the kernel from 4.4.0-91-generic, to 4.4.0-92-generic has caused my system to stop loading up Pantheon-Greeter.  I'm still able to switch my terminal to another terminal, and check dmesg for error messages, which shows that pantheon-greeter segfault's with error 4 from libc-2.23.so.  I can switch to 4.4.0-91-generic, and it'll boot just fine.  Attached is the dmesg bootlog from my computer.
[boot.log.txt](https://github.com/elementary/greeter/files/1243804/boot.log.txt)

**Comment by matzipan** [comment] 2017-09-10 20:19
Could you possibly help us with a stacktrace too? I'm running 4.4.0-93-generic and I don't see any issues.

**Comment by danrabbit** [comment] 2019-03-29 00:10
Closing since this almost certainly can no longer be reproduced

**Closed by danrabbit** 2019-03-29 00:10 UTC

**Comment by hholst80** [comment] 2019-04-04 17:02
```
[  195.064087] pantheon-greete[6654]: segfault at 0 ip 00007f237807c924 sp 00007ffed568dd70 error 4 in libc-2.23.so[7f2378041000+1c0000]
```

**Comment by hholst80** [comment] 2019-04-04 17:22
In my case the problem is caused by a faulty update (not my fault) by the OS that caused the DKMS kernel modules to not work. I am using the NVIDIA video driver.

```
tv@pugsley ~
$ sudo apt-get install --reinstall nvidia-390
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 74,0 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial/main amd64 nvidia-390 amd64 390.87-0ubuntu0~gpu16.04.1 [74,0 MB]
Fetched 74,0 MB in 1min 40s (740 kB/s)
(Reading database ... 225359 files and directories currently installed.)
Preparing to unpack .../nvidia-390_390.87-0ubuntu0~gpu16.04.1_amd64.deb ...
Removing all DKMS Modules
Error! There are no instances of module: nvidia-390
390.87 located in the DKMS tree.
Done.
Unpacking nvidia-390 (390.87-0ubuntu0~gpu16.04.1) over (390.87-0ubuntu0~gpu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Processing triggers for man-db (2.7.5-1) ...
Setting up nvidia-390 (390.87-0ubuntu0~gpu16.04.1) ...
update-initramfs: deferring update (trigger activated)
INFO:Enable nvidia-390
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/lenovo_thinkpad
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/dell_latitude
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/put_your_quirks_here
Loading new nvidia-390-390.87 DKMS files...
Building only for 4.4.0-145-generic
Building for architecture x86_64
Building initial module for 4.4.0-145-generic
ERROR (dkms apport): kernel package linux-headers-4.4.0-145-generic is not supported
Error! Bad return status for module build on kernel: 4.4.0-145-generic (x86_64)
Consult /var/lib/dkms/nvidia-390/390.87/build/make.log for more information.
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for initramfs-tools (0.122ubuntu8.14) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-145-generic

tv@pugsley ~
$
```

**Comment by hholst80** [comment] 2019-04-04 19:34
Problem resolved by installing the latest NVIDIA driver 

```
sudo apt-get install nvidia-418
```
