### ISSUE TITLE
Long login time

### ISSUE THREAD

**Issue by aramsichord** [elementary/greeter#86] opened 2018-01-25 17:39 UTC
Hi,

There is an issue with my elementary os desktop. I get to the login and enter my password, and I have to wait a long time. Sometimes it feels like two minutes just with the wallpaper waiting for the desktop to load. Any ideas on how I can diagnose the issue? I have a lot of non-appcenter apps installed, and I'm thinking it may be one of them, but I don't know the best way to see what's going on immediately after login. Thanks!

**Comment by peteruithoven** [comment] 2018-02-04 19:43
See: https://github.com/elementary/gala/issues/143

**Comment by peteruithoven** [comment] 2019-03-19 11:16
Closing this as a duplicate of elementary/gala#143

**Closed by peteruithoven** 2019-03-19 11:16 UTC
