### ISSUE TITLE
Cursor not active in password field

### ISSUE THREAD

**Issue by seanoneal285** [elementary/greeter#220] opened 2018-12-11 20:54 UTC
When I boot my computer the cursor is not active in the password field. After clicking anywhere on the screen the cursor appears in the password field. When waking up from sleep the cursor is OK.

Also, the mouse pointer is not centred on the greeter screen after boot. (But this is a minor bug.)

I'm on Juno.

**Comment by danrabbit** [comment] 2018-12-11 20:55
Duplicate of #144

**Closed by danrabbit** 2018-12-11 20:55 UTC
