### ISSUE TITLE
Wrong time format for Croatian in Juno, same as in Freya and Loki before

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/greeter#142] opened 2018-07-12 12:57 UTC
Hi.
When Freya came out the time format in Greeter was wrong, showing AM/PM which is not used in Croatian locale. I was involved in fixing this with Croatian translation team.
Then it was an issue again when Loki came out and again I've submitted a fix and it was corrected afterward.
Now the Juno beta1 is out and again this same issue emerges again.
I'm not familiar with Weblate so if anyone can push me in the right direction (and right project) to submit the fix.
Also, why is not possible to fix this issue once for all? I'm not a developer but I believe that this small issue is not something that should be returning every time after new Elementary OS release.

Thank you for your hard work.

Cheers.

**Comment by WebShapedBiz** [comment] 2018-08-22 16:57
Update: In last few days (second part of August) there was an update resulting with a rather silly situation. I now have time format 18:54 PM, so "best of both worlds" :D

**Comment by danrabbit** [comment] 2018-11-13 05:40
Closing as a duplicate of #17

**Closed by danrabbit** 2018-11-13 05:40 UTC

**Comment by w0k3** [comment] 2018-11-26 08:11
@danrabbit is a regression really a duplicate? Original "fix" is closed and I doubt it reopens. Closing every "duplicate" won't solve the problem. So what should we do? Am I missing something? Greeter time in Juno is as buggy as in Freya again.
