### ISSUE TITLE
libvirt-qemu user shows up on the new greeter as disabled

### ISSUE THREAD

**Issue by ibrahimrahman** [elementary/greeter#296] opened 2019-06-27 22:34 UTC
It shouldn't be showing up at all. I'm using the .deb linked in Daniel Foré's Reddit post (3.3.1+r773+pkg61)

**Comment by danrabbit** [comment] 2019-06-27 22:45
Can you do me a favor and paste the output of `id -u libvert-qemu`? I believe users with an ID below something like 1000 shouldn't show

**Comment by ibrahimrahman** [comment] 2019-06-27 22:50
```
❯ id -u libvirt-qemu
64055
```
This issue is specific to the new greeter. It did not show up on the older one (The user has always showed up in the User Accounts setting though. Not sure if it should or not).

**Comment by cassidyjames** [comment] 2019-06-27 23:27
Looks like this is an upstream bug as well. More info at https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1667113

It sounds like we might be able to filter it out somehow?

**Comment by danrabbit** [comment] 2019-06-28 00:07
From the discussion there it sounds like this is confirmed to be an issue either in lightdm or accountsservice and not an issue in a particular greeter implementation. I'd be inclined to mark this as "Out of scope" since a proper fix would occur there. But, I'm also interested in @tintou's opinion

**Comment by codygarver** [comment] 2019-06-28 13:38
If you add `libvirt-qemu` to `hidden-users` in `/etc/lightdm/users.conf` does it fix the issue?

**Comment by ibrahimrahman** [comment] 2019-06-28 14:24
No, the issue persists.

**Comment by ibrahimrahman** [comment] 2019-06-29 14:20
```
printf "[User]\nSystemAccount=true\n" | sudo tee /var/lib/AccountsService/users/libvirt-qemu
sudo systemctl restart accounts-daemon.service 
```
This workaround mentioned [here](https://askubuntu.com/questions/897026/why-do-i-have-a-libvirt-qemu-account-in-lock-switch-account-options-in-ubuntu) stops the user from showing up in both the greeter as well as the User Account settings. However, I'm uncertain if this counts as a proper fix or not

**Comment by endorama** [comment] 2020-01-24 00:29
I found another reference of this issue in upstream Ubuntu: https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1674765

Is confirmed happening on Ubuntu 18.04, which is probably why elementary users see it.

That Bug reference another one: https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/857651, multiple fixes still to be released to see this one fixed completely.

**Comment by danrabbit** [comment] 2020-01-24 00:40
Closing as "out of scope" since this has been confirmed to be an upstream issue

**Closed by danrabbit** 2020-01-24 00:40 UTC
