### ISSUE TITLE
Greeter 3.3.1 r773 alignment with laptop and external monitor

### ISSUE THREAD

**Issue by robertgorbul** [elementary/greeter#301] opened 2019-06-29 07:42 UTC
**OS:** elementary OS 5.0 juno
**Kernel:** x86_64 Linux 4.18.0-25-generic
**Greeter:** pantheon-greeter_3.3.1+r773+pkg61_daily_ubuntu5.0.1_amd64
**Issue:**
When system starts up or locked with external monitor greeter is centered between two screens. External monitor is primary. Wingpanel not affected. After detach and reattach of external monitor greeter is displayed on internal monitor.
![IMG_20190629_103919](https://user-images.githubusercontent.com/9195693/60381255-54166a00-9a5a-11e9-8ab1-a6e6ac9cb465.jpg)
**P.S:** Sorry for the photo. I tried to get a screenshot but result wasn't appropriate unfortunately.

**Comment by peteruithoven** [comment] 2019-06-29 08:48
I'm going to close this as a duplicate of: https://github.com/elementary/greeter/issues/302
I know this one was first, but 302 has a more specific, clearer description.

**Closed by peteruithoven** 2019-06-29 08:48 UTC
