### ISSUE TITLE
How can I disable sleep mode when i turn off pc monitor?

### ISSUE THREAD

**Issue by terrakok** [elementary/greeter#289] opened 2019-06-11 15:25 UTC
When I lock PC screen (Super+L) then monitor turn off and PC get a sleep mode soon.  
I didn't find any options for disable it.
I disabled all variants in Settings -> Power -> ...

Same problem: https://elementaryos.stackexchange.com/questions/8012/how-can-i-disable-sleep-mode-when-i-turn-off-pc-monitor-close-notebook

**Comment by peteruithoven** [comment] 2019-06-11 23:03
I'm afraid this is a duplicate of https://github.com/elementary/greeter/issues/161

**Closed by peteruithoven** 2019-06-11 23:03 UTC
