### ISSUE TITLE
Screen position settings not honored at login screen

### ISSUE THREAD

**Issue by Jthomas54** [elementary/greeter#263] opened 2019-04-02 13:38 UTC
When using a multi-monitor setup, the screen order set in the _Displays_ settings is not honors and seems to revert to the default layout it first had.

My setup has 3 monitors, 2 external and a laptop.  I have set one of the external monitors as the primary screen, which is also ignored, and when locking the machine, the laptop monitor becomes the primary.  The order of the monitors is also backwards making it very awkward to position the mouse.

**Comment by peteruithoven** [comment] 2019-04-02 13:58
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/greeter/issues/65

**Closed by peteruithoven** 2019-04-02 13:58 UTC
