### ISSUE TITLE
Wingpanel is on a Different Monitor than the Greeter

### ISSUE THREAD

**Issue by seesemichaelj** [elementary/greeter#201] opened 2018-11-16 21:57 UTC
The below issue is using the latest from master (as of 7928968). I also have only tested via locking as I can't reboot currently, but will follow up when I have the chance sometime this weekend. This is on a 4 monitors (LoDPI) on a desktop machine.

Wingpanel renders on a different monitor than the monitor with the greeter prompt

**Comment by peteruithoven** [comment] 2019-03-19 10:45
Seems like a duplicate of #65.

**Closed by peteruithoven** 2019-03-19 10:45 UTC
