### ISSUE TITLE
Suspending (graphical glitch + power button only)

### ISSUE THREAD

**Issue by eccathcart** [elementary/greeter#131] opened 2018-07-06 09:47 UTC
![screenshot from 2018-07-06 21 31 48](https://user-images.githubusercontent.com/7200057/42371787-94749596-8164-11e8-89fd-dcdfe94218e8.png)

When suspending the computer or letting it fall asleep, the only way I can awake it again is by holding the power button on my desktop. Pressing anything on the keyboard or clicking the mouse doesn't get it to wake.

Another issue is the graphical issues that appear. When awoken, the wallpaper on the greeter is severely distorted, looking similar to the background in the multitasking view (in above image). The only way to get rid of it is to restart my computer but it reoccurs any time I put my computer to sleep.

~ I'm currently running Juno 5.0 Beta 1. This never happened when I was using Loki. Sorry if I posted this in the wrong place.

**Comment by mdh34** [comment] 2018-07-06 09:49
Are you using NVIDIA drivers?

**Comment by eccathcart** [comment] 2018-07-06 09:50
Yeah, I'm using the latest one that eOS gives (390.48).

**Comment by mdh34** [comment] 2018-07-06 12:10
In that case this is a duplicate of #gala/208 as the greeter uses a stripped down version as a compositor

**Comment by mdh34** [comment] 2018-07-06 14:42
I'll close this so we can track this in one place

**Comment by mdh34** [comment] 2018-07-07 14:10
Oops, turns out we don't actually use gala but rather a basic mutter compositor, so this is a greeter issue

**Comment by eccathcart** [comment] 2018-07-08 08:59
With the recent updates, the wallpaper issue has seem to gone away. I'm still getting the issue where I can only wake my computer by pressing the power button though.

**Comment by peteruithoven** [comment] 2018-09-21 17:03
Maybe clarify you initial comment or open a separate one? It's inconvenient to report on 2 issues in one issue.

**Comment by jlnr** [comment] 2018-10-20 23:11
All the screenshots so far have shown gala, not greeter. Here's a photo of greeter specifically:

![img_3661](https://user-images.githubusercontent.com/70772/47261375-15451300-d4ce-11e8-8d05-c4e76f339f67.jpg)

**Comment by cassidyjames** [comment] 2018-10-23 21:15
Marking as high priority since this affects a lot of people and we continue to get reports of it here and via social media.

**Comment by kbknapp** [comment] 2019-01-28 17:48
Same thing for me, only way to wake from sleep is power button, then get the "neon checkerboard" for a second or two as it wakes. Not using NVidia though. Here's my specs:

```
OS: elementary OS 5.0 Juno x86_64 
Host: Precision 7710 
Kernel: 4.20.3-042003-generic 
Uptime: 4 days, 3 hours, 32 mins 
Packages: 2140 
Shell: zsh 5.4.2 
Resolution: 1920x1080, 1680x1050 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: tilix 
CPU: Intel i7-6820HQ (8) @ 3.600GH 
GPU: AMD Radeon HD 8890M 
Memory: 14468MiB / 64354MiB
```

**Comment by tuxiano** [comment] 2019-03-12 20:12
Hi, 

I have the same issues with juno 5.0, nvidia 1080 (415.27).

Is it possible to switch to GDM3 or another login manager?

**Comment by peteruithoven** [comment] 2019-03-19 11:02
Please try this with the latest version from github. There have been significant changes.

**Comment by tuxiano** [comment] 2019-04-08 07:23
@peteruithoven: thank you. Is there an easier way to test the latest version, without the need to build  greeter with meson?

**Comment by peteruithoven** [comment] 2019-04-08 09:55
@tuxiano no.

**Comment by cassidyjames** [comment] 2019-04-08 16:13
@tuxiano that said, I think the new greeter is pretty close to being released.

**Comment by tuxiano** [comment] 2019-04-14 09:43
@peteruithoven: I managed to build  and install greeter in a VM. Before I try to install it on my productive machine I would like know how to restore the original greeter in case the new greeter isn't working as expected.

Another option:
Is it possible to create an deb file which I can transfer from the VM to my productive machine?

PD. The readme.md file of greeter has some missing information.
libmutter should be libmutter-2-dev
and libaccountsservice-dev is missing.

**Comment by peteruithoven** [comment] 2019-04-14 09:48
> I would like know how to restore the original greeter in case the new greeter isn't working as expected.

I've documented that here for packages in general: 
https://elementary.io/docs/code/os-dev > Restoring original packages

> PD. The readme.md file of greeter has some missing information.
> libmutter should be libmutter-2-dev
> and libaccountsservice-dev is missing.

I think you could try to open a pull request for that ;)
I've found a tutorial: http://archaeogeek.github.io/foss4gukdontbeafraid/fixes/pullrequest.html#a-shortcut-for-fixing-documentation

**Comment by tuxiano** [comment] 2019-05-02 14:11
I build and tried the latest master  a3a5365 and it seams that the issue is gone.

**Comment by tuxiano** [comment] 2019-08-20 06:19
Hi, I would like to know, if the fixed version of the greeter has already been released? I'm asking because the version build with meson looks different to the version available through the apt repositories. The version build with meson shows a small version and the apt version a full screen version of the background image.

**Comment by lenemter** [comment] 2023-12-13 10:57
Closing as fixed.

**Closed by lenemter** 2023-12-13 10:57 UTC
Labels: Priority: High
