### ISSUE TITLE
No Splash Screen while Elementary is loading

### ISSUE THREAD

**Issue by abodedis** [elementary/greeter#554] opened 2021-08-18 20:30 UTC
## What Happened
No Splash screen while the OS is loading.  

## Expected Behavior

A splash screen should correctly display while the OS loads.

## Steps to Reproduce

Occurs on startup.
After POST, there is just a black screen for 20-30 seconds while the OS loads.  

## Platform Information

OS: elementary OS 6 Odin x86_64 
Kernel: 5.11.0-27-generic 
Packages: 1699 (dpkg), 20 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel Xeon W3680 (12) @ 3.326GHz 
GPU: NVIDIA GeForce GT 1030 
Memory: 1370MiB / 24047MiB

**Comment by abodedis** [comment] 2021-08-21 14:36
Clarification: On an older system with BIOS and no "manufacturers logo" (see platform above), screen may be blank throughout loading of OS.  

Suggest to check system to see if manufacturer's logo is available, if not, display the elementary OS logo in supported monitor resolution.

**Comment by abodedis** [comment] 2021-08-21 14:37
Clarification: On an older system with BIOS and no manufacturers logo (see platform above), screen may be blank throughout loading of OS.  

Suggest to check system to see if manufacturer's logo is available, if not, display the elementary OS logo in supported monitor resolution.

**Comment by dennismayr** [comment] 2021-08-22 01:42
I'm also affected by this, and the lack of a splash screen, which looks like `plymouth` failing to work, has the side effect of exposing the boot log to the screen in framebuffer mode when logging off the user session back to the greeter, or rebooting/shutting down.

This doesn't happen in the equivalent Ubuntu and Kubuntu installations, as I've tried over the past couple of days.

Hardware:
Lenovo ThinkPad T410s (2013)
CPU: Intel i5 540-M
Dual graphics (Optimus): Intel HD Graphics (Ironlake) + NVIDIA NVS3100M (512Mb, `nouveau` driver)

**Comment by 4jNsY6fCVqZv** [comment] 2021-12-03 12:11
Is this really a Greeter issue? Or rather a Plymouth issue? https://github.com/elementary/plymouth-theme/issues/17

**Comment by dennismayr** [comment] 2021-12-03 12:14
After having found that other issue, I've concluded that it's a `plymouth` issue and not a greeter problem, as initially suspected.

**Comment by 4jNsY6fCVqZv** [comment] 2021-12-03 12:28
Perhaps this issue can be closed as duplicate or out of scope if the elementary team can provide feedback on this issue?

**Comment by dennismayr** [comment] 2021-12-03 12:38
It's definitely a duplicate of the same problem, so it can be closed.

**Comment by davidmhewitt** [comment] 2022-01-25 09:47
This is definitely not a greeter issue, the linked elementary/plymouth-theme#17 issue is the correct place for this and there are additional details there. So I'm closing this as a duplicate.

**Closed by davidmhewitt** 2022-01-25 09:47 UTC
