### ISSUE TITLE
Allow users to set a custom greeter wallpaper

### ISSUE THREAD

**Issue by mderrien29** [elementary/greeter#330] opened 2019-08-27 22:56 UTC
The default grey background is quite ugly, i think most users (myself included) would like to change it without recompiling the application.

**Comment by caglarturali** [comment] 2019-08-28 07:32
Here is my take on what @GammaGames described/demonstrated above. There is no transition between the screens since it's a gif composed of two images, but just imagine as if there is. :blush:

![](https://raw.githubusercontent.com/caglarturali/elementaryos-greeter-ideas/master/sample.gif)

And here are the individual screenshots:
[Sample 1](https://github.com/caglarturali/elementaryos-greeter-ideas/blob/master/sample-01.jpg?raw=true)
[Sample 2](https://github.com/caglarturali/elementaryos-greeter-ideas/blob/master/sample-02.jpg?raw=true)

**Comment by FernandoGarcia** [comment] 2019-08-28 21:25
In case someone is interested to back to old version as temporary solution here the steps:

1 - Make a backup of your system using Time Shift in case something goes wrong.

```
sudo add-apt-repository -y ppa:teejee2008/ppa
sudo apt-get update
sudo apt-get install timeshift
```

After open the application and create a backup.

2 - Uninstall Greeter

`sudo apt remove pantheon-greeter`

3 - Download the [3.2 greeter package](https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+sourcepub/8445286/+listing-archive-extra) according to your hardware.

Install the package using Eddy.

4 - Hold Greeter version to prevent it being updated again.

`sudo apt-mark hold pantheon-greeter`

Warning: Don't close the session before install old Greeter version otherwise you will get a black screen.

**Comment by cassidyjames** [comment] 2019-08-29 08:31
The gray is not a wallpaper, it's the same system-layer texture we use in Gala underneath the session. We can iterate on the design, but I'm closing this as it is not the same as allowing a greeter wallpaper; that would be a duplicate of #257 anyway.

**Closed by cassidyjames** 2019-08-29 08:31 UTC
