### ISSUE TITLE
Can't login using tty

### ISSUE THREAD

**Issue by IamLizu** [elementary/greeter#238] opened 2019-03-03 07:42 UTC
I can't use tty(1-6) to login. After I type my username, password can't be entered rather it refreshes and tells me to enter username again. Something like [this](https://vimeo.com/320996187). I have seen other users reporting same thing on eOS stack exchange site. Actually it was working last time I checked. But after seeing a post that says someone's facing this, i see I now also have the problem. So maybe its due to any recent update.

**Comment by peteruithoven** [comment] 2019-03-03 09:09
Could you clarify what you type / what keys you press during that video?
It almost looks like enter is pressed quickly when the password is asked?
Could you link to the StackExchange question?

I think this has little to nothing to do with the layers from elementary OS though. Maybe check if other Ubuntu users experience this issue?

**Comment by IamLizu** [comment] 2019-03-03 12:35
The video linked above is from a user that faced it first. Yes it seems <kbd>Enter</kbd> is pressed quickly right after but it was not. I am sure because this happens in my case too and I am very sure that keyboard is working fine. Here is the post on eOS StackExchange site : https://elementaryos.stackexchange.com/questions/18405/cannot-login-from-tty-auto-r-when-tty-login

**Comment by peteruithoven** [comment] 2019-03-19 10:15
This sounds a lot like: https://askubuntu.com/questions/1113704/tty-doesnt-wait-for-password
There are also a lot of duplicate questions that point back to that one. 

I'm closing this issue here, since I really doubt this is caused by anything elementary OS adds.

**Closed by peteruithoven** 2019-03-19 10:15 UTC
