### ISSUE TITLE
Respect user switch and focus on the right card in greeter

### ISSUE THREAD

**Issue by yelloball** [elementary/greeter#300] opened 2019-06-28 16:33 UTC
If the wingpanel drop-down is used to switch user, by selecting another user, then the greeter doesn't focus on the user's (not currently logged-in) card; rather the focus is still with the currently logged in user.

**Comment by cassidyjames** [comment] 2019-06-28 20:32
I can't reproduce this. When I select a user from the account switcher, the greeter focuses that user for me.

**Comment by yelloball** [comment] 2019-06-28 21:41
![to_gh](https://user-images.githubusercontent.com/14001336/60372797-8f457880-9a1b-11e9-87fa-9c9a50e299a6.gif)
This is what I was doing; just to clarify.

**Comment by danrabbit** [comment] 2021-06-18 17:25
Hm, I can't confirm this anymore. The correct user seems to be pre-selected here. I was able to reproduce a stacking/order issue, but that was resolved with the switch to Hdy.Carousel. This may have been resolved already.

Closing since two people are unable to reproduce. Please feel free to reopen if someone else can reproduce the issue

**Closed by danrabbit** 2021-06-18 17:25 UTC
Labels: Status: Incomplete
