### ISSUE TITLE
Wrong placement of Login prompt on laptops with closed lid

### ISSUE THREAD

**Issue by Amphyby** [elementary/greeter#146] opened 2018-07-16 08:45 UTC
Imagine you are using laptop as desktop. Lid is always closed and monitor stands on it, some external IO devices connected. Meanwhile BIOS and Windows determine it and showing info only on available screen (monitor), Elementary opens login prompt on the (closed) Lid-screen and there is absolutely no way you can see whats happening except blind-entering password or opening laptop's lid.

**Comment by peteruithoven** [comment] 2019-03-19 10:42
Seems like a duplicate of #65 indeed.

**Closed by peteruithoven** 2019-03-19 10:42 UTC
