### ISSUE TITLE
Should the password input field give me a visual feedback if my password is not accepted because the login is still locked by Screen Time & Limits settings?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/greeter#513] opened 2021-03-05 09:33 UTC
As a first impulse I had thought of the Greeter's handling of Caps Lock, for which I do get visual feedback.
Additionally I wonder if it makes sense to display when the restrictions will be revoked again. For example as a countdown in hours/minutes (time left) or the fixed time.

**Comment by danrabbit** [comment] 2021-03-08 17:32
Closing as a duplicate of #430. In fact you reported that issue as well xD

**Closed by danrabbit** 2021-03-08 17:32 UTC
