### ISSUE TITLE
Multiple monitors are recognized as one big monitor

### ISSUE THREAD

**Issue by veraguido** [elementary/greeter#302] opened 2019-06-29 08:32 UTC
In this case 2 monitors (different resolutions) are recognized as one very wide monitor, placing the login details vignettes and the clock between both of them
![IMG_20190629_092735](https://user-images.githubusercontent.com/5069483/60381688-9c308f00-9a50-11e9-84d5-7ebab1e6a857.jpg)

GPU: nvidia 1050ti (prime)

**Comment by peteruithoven** [comment] 2019-06-29 08:49
@robertgorbul noticed the same, details from https://github.com/elementary/greeter/issues/301:

**OS:** elementary OS 5.0 juno
**Kernel:** x86_64 Linux 4.18.0-25-generic
**Greeter:** pantheon-greeter_3.3.1+r773+pkg61_daily_ubuntu5.0.1_amd64
**Issue:**
When system starts up or locked with external monitor greeter is centered between two screens. External monitor is primary. Wingpanel not affected. After detach and reattach of external monitor greeter is displayed on internal monitor.
![IMG_20190629_103919](https://user-images.githubusercontent.com/9195693/60381255-54166a00-9a5a-11e9-8ab1-a6e6ac9cb465.jpg)
**P.S:** Sorry for the photo. I tried to get a screenshot but result wasn't appropriate unfortunately.

**Comment by peteruithoven** [comment] 2019-07-01 19:07
Are there any situations where you don't see this behavior? 
@robertgorbul are you also using a NVIDIA card?

I can't reproduce this issue: 
![IMG_20190701_205542-2000](https://user-images.githubusercontent.com/523210/60460385-e3cb3c80-9c43-11e9-8b82-67201f4e24aa.jpg)

**Comment by danrabbit** [comment] 2019-07-01 19:19
I'm also unable to reproduce this issue using a USB C output on my notebook for an external HDMI TV.

**Comment by robertgorbul** [comment] 2019-07-01 19:41
@peteruithoven it's always the same. 
My laptop have hybrid graphics - Intel HD4000 + AMD Radeon 8750M. 
Kernel 4.18.0-25-generic. Mesa 19.1.0 from Padoka stable.
Internal screen is 1366x768 as secondary and external Benq 2560x1440 as primary connected through HDMI. And just fyi I have a custom modeline:
```
  1 Section "Monitor"
  2   Identifier "HDMI-1"
  3   Modeline "2560x1440_55.00" 221.00  2560 2608 2640 2720  1440 1443 1447 1478  +HSync -VSync
  4   Option "PreferredMode" "2560x1440_55.00"
  5 EndSection
``` 
![Screenshot from 2019-07-01 22-39-59](https://user-images.githubusercontent.com/9195693/60462165-3f4ff700-9c51-11e9-98a8-0321cdf9e815.png)
No other custom tools or else. I've removed tlp and powertop optimizations if it's important. Just HWE Kernel and Mesa from padoka. If you need logs please tell me how can I get it for you.

**Comment by peteruithoven** [comment] 2019-07-01 23:49
@robertgorbul I don't know what a modeline is. That looks like something that could influence things. Any change you could disable it for a moment? We can't find people who can reproduce the issue. 
Any change you could build and install https://github.com/elementary/greeter/pull/307, see if that fixes things?

**Comment by robertgorbul** [comment] 2019-07-02 08:52
@peteruithoven basically custom modeline just allows me to run 2560x1440 at 55Hz because integrated video card don't have enough juice but anyway I will test greeter at standard resolution just in case. Considering building greeter from #307 - yes, I will try to do that.

**Comment by robertgorbul** [comment] 2019-07-02 19:22
@peteruithoven @danrabbit 
Results are:
1. Greeter 3.3.1+r773 **without** custom modeline -> monitors recognized correctly
2. Greeter build against #307 **with** custom modeline -> monitors recognized correctly

**Comment by peteruithoven** [comment] 2019-07-02 19:40
@robertgorbul thanks for trying, that's great news!

@veraguido Could you try #307 as well? Any change you're also using a custom modeline?

**Comment by veraguido** [comment] 2019-07-02 19:42
Hey, sorry I'm on holidays and will be back next week. Will post here as soon as I can

**Comment by veraguido** [comment] 2019-07-06 21:12
I've tried latest build from master and I have the same results than before.

**Comment by peteruithoven** [comment] 2019-07-07 00:17
@veraguido no please try the pull request I referenced earlier, that's the `get-primary-monitor` branch.

**Comment by veraguido** [comment] 2019-07-07 10:06
Oh, sorry about that, I thought it was already merged.
I can confirm the bug is fixed with that branch (get-primary-monitor) :+1:

**Comment by peteruithoven** [comment] 2019-07-07 11:46
Great to hear! 
Normally we close issues when the PR (pull request) is accepted (merged) ;)

**Comment by peteruithoven** [comment] 2019-07-07 11:47
@veraguido btw, any change you're also using a custom modeline? Or anything similar?

**Comment by veraguido** [comment] 2019-07-07 16:29
Not really, monitors are setup as per default (both at 60hz) the only noticeable difference is the resolution, one is 4k the other one is a 1080p.

**Comment by danrabbit** [comment] 2019-08-13 15:24
Closing since #307 was merged

**Closed by danrabbit** 2019-08-13 15:24 UTC
Labels: Priority: High, Status: Confirmed
