### ISSUE TITLE
"Artifacts" after suspend\sleep mode

### ISSUE THREAD

**Issue by profiterole38** [elementary/greeter#169] opened 2018-10-20 11:12 UTC
I have some problem with displaying 'background elements' after my pc returned from suspend\sleep mode
Nvidia 1050. Official drivers from site.
Example in attach. Its a multitask screen
Same case happening in "Lock screen"
![img_20181020_180750](https://user-images.githubusercontent.com/44316886/47254979-887d6380-d493-11e8-8d97-292e39040c51.jpg)

**Comment by cassidyjames** [comment] 2018-10-20 16:10
This is a duplicate of https://github.com/elementary/gala/issues/21 which has been fixed in master.

**Closed by cassidyjames** 2018-10-20 16:10 UTC

**Comment by jlnr** [comment] 2018-10-20 16:58
This is a duplicate of #131. The Nvidia artifact bug is still present in the greeter master.

**Comment by cassidyjames** [comment] 2018-10-20 20:04
@jlnr well, it's a duplicate of both; the screenshot and majority of the description are describing Gala. But yes, the greeter side is being tracked at #131 if there is still an issue there.
