### ISSUE TITLE
Built-in Fingerprint Login

### ISSUE THREAD

**Issue by Fatih20** [elementary/greeter#347] opened 2019-09-02 06:55 UTC
Would be cool if you guys can use some [code](https://github.com/terjr/fingerprint-gui) from here to make a fingerprint utility built-in to elementary OS.

**Comment by reorr** [comment] 2019-09-02 08:51
Duplicate of https://github.com/elementary/switchboard-plug-useraccounts/issues/5

**Comment by danrabbit** [comment] 2019-09-04 15:34
Yes, the Greeter theoretically already supports fingerprint login. We just need an interface to set up fingerprints for a user. Closing since this should already be fixed for Greeter

**Closed by danrabbit** 2019-09-04 15:34 UTC

**Comment by Fatih20** [comment] 2019-09-04 15:36
What do you mean already fixed? Has the commit already exists, just need to be reviewed?

**Comment by danrabbit** [comment] 2019-09-04 15:37
As I said, the Greeter [already supports fingerprint login](https://github.com/elementary/greeter/blob/master/src/FPrintUtils.vala). The interface for configuring fingerprint login needs to be built in System Settings

**Comment by Fatih20** [comment] 2019-09-04 15:41
So, if that's done, both of these will happen?

1. I don't need to install fingerprint-gui for fingerprint login since the functionality is built-in
2. Contributors would be able to better integrate fingerprint login to the greeter so that the insterface provided for logging in would be more aesthetically pleasing than the one provided by fingerprint-gui.

**Comment by matzipan** [comment] 2019-09-05 11:59
The Greeter itself supports fingerprint login. I wrote it myself for the Gdk one a long time ago. It is not up to the Greeter to set up your fingerprints.
