### ISSUE TITLE
Login screen clock showing wrong time

### ISSUE THREAD

**Issue by kenedyroger** [elementary/greeter#383] opened 2019-11-28 16:48 UTC
When user lock-screen with Ctrl+L keys, after a time the computer will turn off screen and sleep/hibernate.
When user wakeup the machine and login screen is showed to him, the clock showed is completly wrong it show a past time, I think that it is showing the time at moment where computer was sleep.

My system is updated and running :
elementary OS 5.0 Juno
Linux 4.15.0-70-generic
GTK 3.22.30

**Comment by danduta** [comment] 2020-09-10 12:09
Reproduces on 5.1.4 Hera.

Linux 5.3.0-53 generic
GTK 3.22.30

**Comment by vjr** [comment] 2020-09-13 17:06
Duplicate of #306

**Closed** 2020-12-14 09:35 UTC
