### ISSUE TITLE
The result of the display setting script is not reflected

### ISSUE THREAD

**Issue by Hayao0819** [elementary/greeter#504] opened 2021-02-04 13:53 UTC
## What Happened
I am setting the display layout with xrandr with display-setup-script in lightdm.coonf.
This works fine with Slick-Greeter and Webki2-Greeter.
However, it does not work properly with Pantheon-Greeter.
The script appears to be running, but the display settings are incorrect. 
I tried some tricks such as adding a delay and setting it as a greeter-setup-script, but the result did not change.

## Expected Behavior
It should be set up just like any other Greeter.

## Platform Information
Arch Linux (no testing repo)
lightdm-pantheon-greeter 5.0.4-2
lightdm 1:1.30.0-4

**Comment by tintou** [comment] 2021-02-04 13:55
Duplicate of https://github.com/elementary/greeter/issues/404 see the comments for the workaround.

**Closed by tintou** 2021-02-04 13:55 UTC

**Comment by Hayao0819** [comment] 2021-02-04 14:02
I have already read that issue
But 404 is a configuration file by Xorg.
In my case it is a command by xrandr.
And I'm using Xfce and don't want to use Gnome's settings.

**Comment by tintou** [comment] 2021-02-04 14:05
They are really the same configuration mechanism which isn't supported by libmutter (in use in the greeter).

**Comment by Hayao0819** [comment] 2021-02-05 09:14
I understood
