### ISSUE TITLE
Greeter shows unwanted 'libvirt-qemu' system process user (used for virtualization)

### ISSUE THREAD

**Issue by dennismayr** [elementary/greeter#462] opened 2020-08-22 16:19 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When booting the OS after installing KVM prerequisites to use the Android Studio emulator (`qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`), a new system user is created: `libvirt-qemu`.

![](https://imgur.com/bKhoShN.png)
![](https://imgur.com/mbXYVgn.png)

This is a non-human system user for processes; it has no login details. Listing it as a login option is unwanted.
![](https://imgur.com/mBUCZJw.png)

### To Reproduce
1. Open a Temrinal window and install KVM prerequisites for Android Studio emulator: `sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils`
2. Open _System Settings -> User Accounts_
3. Check the user list: see that there's a new `libvirt-qemu` account with a padlock icon

### Expected behavior
System-process users such as `libvirt-qemu` should be hidden from the greeter.

## Platform Information
 - OS: elementary OS
 - OS Version: 5.1.7 Hera
 - Hardware info: 
   * Intel® Core™ i5 CPU M540 @ 2.53GHz
   * NVIDIA Corporation GT218M [NVS 3100M] (rev a2)
   * 8Gb RAM

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by jlnr** [comment] 2020-08-30 21:01
Duplicate of #328

**Closed** 2021-08-23 18:42 UTC
