### ISSUE TITLE
if set wallpaper as centered or as spanned on lock screen still show zoom

### ISSUE THREAD

**Issue by torikulhabib** [elementary/greeter#122] opened 2018-06-21 14:27 UTC
![screenshot from 2018-06-21 19-26-38](https://user-images.githubusercontent.com/26135527/41725333-b2022398-7599-11e8-8bbf-7adede671ec7.png)
![screenshot from 2018-06-21 19-25-34](https://user-images.githubusercontent.com/26135527/41725352-bebd04c2-7599-11e8-9f5a-3873a7252543.png)
![unnamed](https://user-images.githubusercontent.com/26135527/41725382-cefe49cc-7599-11e8-86bd-a58f7744d0f2.jpg)

**Comment by danrabbit** [comment] 2018-06-21 18:58
Closing as a duplicate of #9

**Closed by danrabbit** 2018-06-21 18:58 UTC
