### ISSUE TITLE
Switching user requires login twice

### ISSUE THREAD

**Issue by bcamargogui** [elementary/greeter#613] opened 2022-05-30 14:06 UTC
### What Happened?

When switching session between users, after the login page to the new user, the display freezes and redirect to login page again

### Steps to Reproduce

1. Having 2 users, log on one
2. On top right corner, click on power icon, then click on the other user
3. Input your password and submit
4. Move your mouse between the desktop and the system will redirect you to the login page

### Expected Behavior

Once you already have pass the login page, the system should not ask for the login again

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

elementary OS 6.1 Jólnir
Built on Ubuntu 20.04.3 LTS
Linux 5.13.0-44-generic

IdeaPad-Gaming-3-15IMH05-2aed92cd
Hexa-Core Intel® Core™ i7-10750H CPU @ 2.60GHz
Intel® UHD Graphics (CML GT2)
NVIDIA Corporation
15.5 GiB memory
498.7 GB storage

**Comment by Kissanth** [comment] 2022-06-11 13:52
Ya me also have the issue

**Comment by lenemter** [comment] 2024-01-27 15:09
I cannot reproduce the issue. It may have been fixed in https://github.com/canonical/lightdm/pull/288. If you still encounter the issue please reply here.

**Closed by lenemter** 2024-01-27 15:09 UTC
