### ISSUE TITLE
User accounts cannot be selected by cliking on the icons

### ISSUE THREAD

**Issue by uncertainquark** [elementary/greeter#94] opened 2018-03-29 10:17 UTC
You cannot change selection of user account by clicking on the icons.
![img_0947-400x1000](https://user-images.githubusercontent.com/22585732/38083878-83859a04-3368-11e8-94bc-e71553d48bea.JPG)

**Comment by danrabbit** [comment] 2018-03-31 16:47
Closing as a duplicate of #80. This is fixed in master :)

**Closed by danrabbit** 2018-03-31 16:47 UTC
